import 'package:get/get.dart';

class LanguageManager extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'zh_CN': {
      'appName': 'safeVpn',
      'FIX': 'FIX',
      "VPN": "VPN",
      'Log in': 'Log in',
      'Sign Up': 'Sign Up',
      'Enter email address': "Enter email address",
      'Email Address': "Email Address",
      'By signing up,I agree to the': "By signing up,I agree to the ",
      'private policy': "private policy",
      'Log in with Google': "Log in with Google",
      'Get A Plan': "Get A Plan",
      'That Works For You': "That Works For You",
      'sub_desc':
          "Stable and 10 times high speed Watch HD videos without freezing Remove annoyed Ads banners Connect up to 5 different devices",
      "Deleting an Account": "Deleting an Account",
      "Delete account on": "Delete account on",
      "SafeVPN": "SafeVPN",
      "delete_desc":
          "1、After submitting, you will receive an email confirming the deletion, click the link in the email to complete the account deletion.2、 This will delete all your data and it cannot be recovered.",
      "Submit": "Submit",
      "Email has been sent": "Email has been sent",
      "send_email_desc":
          "Please go to your mailbox to receive the email, and click the link in the email to complete the account deletion.",
      "Account has been": "Account has been",
      "deleted": "deleted",
      "Return Home": "Return Home",
      "Verification": "Verification",
      "Resend code in": "Resend code in ",
      "verification_desc":
          "We have sent a verification code to your email. Please enter that code to complete",
      "Bind Referrer": "Bind Referrer",
      "Enter points": "Enter points",
      "Referrer code": "Referrer code",
      "Withdraw": "Withdraw",
      "Assets": "Assets",
      "Points": "Points",
      "Enter account": "Enter account",
      "Account": "Account",
      "Enter name": "Enter name",
      "Name": "Name",
    },
    'en_US': {
      'appName': 'safeVpn',
      'FIX': 'FIX',
      "VPN": "VPN",
      'Log in': 'Log in',
      'Sign Up': 'Sign Up',
      'Enter email address': "Enter email address",
      'Email Address': "Email Address",
      'By signing up,I agree to the': "By signing up,I agree to the ",
      'private policy': "private policy",
      'Log in with Google': "Log in with Google",
      'Get A Plan': "Get A Plan",
      'That Works For You': "That Works For You",
      'sub_desc':
          "Stable and 10 times high speed Watch HD videos without freezing Remove annoyed Ads banners Connect up to 5 different devices",
      "Deleting an Account": "Deleting an Account",
      "Delete account on": "Delete account on",
      "SafeVPN": "SafeVPN",
      "delete_desc":
          "1、After submitting, you will receive an email confirming the deletion, click the link in the email to complete the account deletion.2、 This will delete all your data and it cannot be recovered.",
      "Submit": "Submit",
      "Email has been sent": "Email has been sent",
      "send_email_desc":
          "Please go to your mailbox to receive the email, and click the link in the email to complete the account deletion.",
      "Account has been": "Account has been",
      "deleted": "deleted",
      "Return Home": "Return Home",
      "Verification": "Verification",
      "Resend code in": "Resend code in ",
      "verification_desc":
          "We have sent a verification code to your email. Please enter that code to complete",
      "Bind Referrer": "Bind Referrer",
      "Enter points": "Enter points",
      "Referrer code": "Referrer code",
      "Withdraw": "Withdraw",
      "Assets": "Assets",
      "Points": "Points",
      "Enter account": "Enter account",
      "Account": "Account",
      "Enter name": "Enter name",
      "Name": "Name",
    },
    'de_DE': {
      'appName': 'safeVpn',
      'FIX': 'FIX',
      "VPN": "VPN",
      'Log in': 'Log in',
      'Sign Up': 'Sign Up',
      'Enter email address': "Enter email address",
      'Email Address': "Email Address",
      'By signing up,I agree to the': "By signing up,I agree to the ",
      'private policy': "private policy",
      'Log in with Google': "Log in with Google",
      'Get A Plan': "Get A Plan",
      'That Works For You': "That Works For You",
      'sub_desc':
          "Stable and 10 times high speed Watch HD videos without freezing Remove annoyed Ads banners Connect up to 5 different devices",
      "Deleting an Account": "Deleting an Account",
      "Delete account on": "Delete account on",
      "SafeVPN": "SafeVPN",
      "delete_desc":
          "1、After submitting, you will receive an email confirming the deletion, click the link in the email to complete the account deletion.2、 This will delete all your data and it cannot be recovered.",
      "Submit": "Submit",
      "Email has been sent": "Email has been sent",
      "send_email_desc":
          "Please go to your mailbox to receive the email, and click the link in the email to complete the account deletion.",
      "Account has been": "Account has been",
      "deleted": "deleted",
      "Return Home": "Return Home",
      "Verification": "Verification",
      "Resend code in": "Resend code in ",
      "verification_desc":
          "We have sent a verification code to your email. Please enter that code to complete",
      "Bind Referrer": "Bind Referrer",
      "Enter points": "Enter points",
      "Referrer code": "Referrer code",
      "Withdraw": "Withdraw",
      "Assets": "Assets",
      "Points": "Points",
      "Enter account": "Enter account",
      "Account": "Account",
      "Enter name": "Enter name",
      "Name": "Name",
    },
    'es_ES': {
      'appName': 'safeVpn',
      'FIX': 'FIX',
      "VPN": "VPN",
      'Log in': 'Log in',
      'Sign Up': 'Sign Up',
      'Enter email address': "Enter email address",
      'Email Address': "Email Address",
      'By signing up,I agree to the': "By signing up,I agree to the ",
      'private policy': "private policy",
      'Log in with Google': "Log in with Google",
      'Get A Plan': "Get A Plan",
      'That Works For You': "That Works For You",
      'sub_desc':
          "Stable and 10 times high speed Watch HD videos without freezing Remove annoyed Ads banners Connect up to 5 different devices",
      "Deleting an Account": "Deleting an Account",
      "Delete account on": "Delete account on",
      "SafeVPN": "SafeVPN",
      "delete_desc":
          "1、After submitting, you will receive an email confirming the deletion, click the link in the email to complete the account deletion.2、 This will delete all your data and it cannot be recovered.",
      "Submit": "Submit",
      "Email has been sent": "Email has been sent",
      "send_email_desc":
          "Please go to your mailbox to receive the email, and click the link in the email to complete the account deletion.",
      "Account has been": "Account has been",
      "deleted": "deleted",
      "Return Home": "Return Home",
      "Verification": "Verification",
      "Resend code in": "Resend code in ",
      "verification_desc":
          "We have sent a verification code to your email. Please enter that code to complete",
      "Bind Referrer": "Bind Referrer",
      "Enter points": "Enter points",
      "Referrer code": "Referrer code",
      "Withdraw": "Withdraw",
      "Assets": "Assets",
      "Points": "Points",
      "Enter account": "Enter account",
      "Account": "Account",
      "Enter name": "Enter name",
      "Name": "Name",
    },
    'fa_IR': {
      'appName': 'safeVpn',
      'FIX': 'FIX',
      "VPN": "VPN",
      'Log in': 'Log in',
      'Sign Up': 'Sign Up',
      'Enter email address': "Enter email address",
      'Email Address': "Email Address",
      'By signing up,I agree to the': "By signing up,I agree to the ",
      'private policy': "private policy",
      'Log in with Google': "Log in with Google",
      'Get A Plan': "Get A Plan",
      'That Works For You': "That Works For You",
      'sub_desc':
          "Stable and 10 times high speed Watch HD videos without freezing Remove annoyed Ads banners Connect up to 5 different devices",
      "Deleting an Account": "Deleting an Account",
      "Delete account on": "Delete account on",
      "SafeVPN": "SafeVPN",
      "delete_desc":
          "1、After submitting, you will receive an email confirming the deletion, click the link in the email to complete the account deletion.2、 This will delete all your data and it cannot be recovered.",
      "Submit": "Submit",
      "Email has been sent": "Email has been sent",
      "send_email_desc":
          "Please go to your mailbox to receive the email, and click the link in the email to complete the account deletion.",
      "Account has been": "Account has been",
      "deleted": "deleted",
      "Return Home": "Return Home",
      "Verification": "Verification",
      "Resend code in": "Resend code in ",
      "verification_desc":
          "We have sent a verification code to your email. Please enter that code to complete",
      "Bind Referrer": "Bind Referrer",
      "Enter points": "Enter points",
      "Referrer code": "Referrer code",
      "Withdraw": "Withdraw",
      "Assets": "Assets",
      "Points": "Points",
      "Enter account": "Enter account",
      "Account": "Account",
      "Enter name": "Enter name",
      "Name": "Name",
    },
    'fr_FR': {
      'appName': 'safeVpn',
      'FIX': 'FIX',
      "VPN": "VPN",
      'Log in': 'Log in',
      'Sign Up': 'Sign Up',
      'Enter email address': "Enter email address",
      'Email Address': "Email Address",
      'By signing up,I agree to the': "By signing up,I agree to the ",
      'private policy': "private policy",
      'Log in with Google': "Log in with Google",
      'Get A Plan': "Get A Plan",
      'That Works For You': "That Works For You",
      'sub_desc':
          "Stable and 10 times high speed Watch HD videos without freezing Remove annoyed Ads banners Connect up to 5 different devices",
      "Deleting an Account": "Deleting an Account",
      "Delete account on": "Delete account on",
      "SafeVPN": "SafeVPN",
      "delete_desc":
          "1、After submitting, you will receive an email confirming the deletion, click the link in the email to complete the account deletion.2、 This will delete all your data and it cannot be recovered.",
      "Submit": "Submit",
      "Email has been sent": "Email has been sent",
      "send_email_desc":
          "Please go to your mailbox to receive the email, and click the link in the email to complete the account deletion.",
      "Account has been": "Account has been",
      "deleted": "deleted",
      "Return Home": "Return Home",
      "Verification": "Verification",
      "Resend code in": "Resend code in ",
      "verification_desc":
          "We have sent a verification code to your email. Please enter that code to complete",
      "Bind Referrer": "Bind Referrer",
      "Enter points": "Enter points",
      "Referrer code": "Referrer code",
      "Withdraw": "Withdraw",
      "Assets": "Assets",
      "Points": "Points",
      "Enter account": "Enter account",
      "Account": "Account",
      "Enter name": "Enter name",
      "Name": "Name",
    },
    'hi_IN': {
      'appName': 'safeVpn',
      'FIX': 'FIX',
      "VPN": "VPN",
      'Log in': 'Log in',
      'Sign Up': 'Sign Up',
      'Enter email address': "Enter email address",
      'Email Address': "Email Address",
      'By signing up,I agree to the': "By signing up,I agree to the ",
      'private policy': "private policy",
      'Log in with Google': "Log in with Google",
      'Get A Plan': "Get A Plan",
      'That Works For You': "That Works For You",
      'sub_desc':
          "Stable and 10 times high speed Watch HD videos without freezing Remove annoyed Ads banners Connect up to 5 different devices",
      "Deleting an Account": "Deleting an Account",
      "Delete account on": "Delete account on",
      "SafeVPN": "SafeVPN",
      "delete_desc":
          "1、After submitting, you will receive an email confirming the deletion, click the link in the email to complete the account deletion.2、 This will delete all your data and it cannot be recovered.",
      "Submit": "Submit",
      "Email has been sent": "Email has been sent",
      "send_email_desc":
          "Please go to your mailbox to receive the email, and click the link in the email to complete the account deletion.",
      "Account has been": "Account has been",
      "deleted": "deleted",
      "Return Home": "Return Home",
      "Verification": "Verification",
      "Resend code in": "Resend code in ",
      "verification_desc":
          "We have sent a verification code to your email. Please enter that code to complete",
      "Bind Referrer": "Bind Referrer",
      "Enter points": "Enter points",
      "Referrer code": "Referrer code",
      "Withdraw": "Withdraw",
      "Assets": "Assets",
      "Points": "Points",
      "Enter account": "Enter account",
      "Account": "Account",
      "Enter name": "Enter name",
      "Name": "Name",
    },
    'in': {
      'appName': 'safeVpn',
      'FIX': 'FIX',
      "VPN": "VPN",
      'Log in': 'Log in',
      'Sign Up': 'Sign Up',
      'Enter email address': "Enter email address",
      'Email Address': "Email Address",
      'By signing up,I agree to the': "By signing up,I agree to the ",
      'private policy': "private policy",
      'Log in with Google': "Log in with Google",
      'Get A Plan': "Get A Plan",
      'That Works For You': "That Works For You",
      'sub_desc':
          "Stable and 10 times high speed Watch HD videos without freezing Remove annoyed Ads banners Connect up to 5 different devices",
      "Deleting an Account": "Deleting an Account",
      "Delete account on": "Delete account on",
      "SafeVPN": "SafeVPN",
      "delete_desc":
          "1、After submitting, you will receive an email confirming the deletion, click the link in the email to complete the account deletion.2、 This will delete all your data and it cannot be recovered.",
      "Submit": "Submit",
      "Email has been sent": "Email has been sent",
      "send_email_desc":
          "Please go to your mailbox to receive the email, and click the link in the email to complete the account deletion.",
      "Account has been": "Account has been",
      "deleted": "deleted",
      "Return Home": "Return Home",
      "Verification": "Verification",
      "Resend code in": "Resend code in ",
      "verification_desc":
          "We have sent a verification code to your email. Please enter that code to complete",
      "Bind Referrer": "Bind Referrer",
      "Enter points": "Enter points",
      "Referrer code": "Referrer code",
      "Withdraw": "Withdraw",
      "Assets": "Assets",
      "Points": "Points",
      "Enter account": "Enter account",
      "Account": "Account",
      "Enter name": "Enter name",
      "Name": "Name",
    },
    'in_ID': {
      'appName': 'safeVpn',
      'FIX': 'FIX',
      "VPN": "VPN",
      'Log in': 'Log in',
      'Sign Up': 'Sign Up',
      'Enter email address': "Enter email address",
      'Email Address': "Email Address",
      'By signing up,I agree to the': "By signing up,I agree to the ",
      'private policy': "private policy",
      'Log in with Google': "Log in with Google",
      'Get A Plan': "Get A Plan",
      'That Works For You': "That Works For You",
      'sub_desc':
          "Stable and 10 times high speed Watch HD videos without freezing Remove annoyed Ads banners Connect up to 5 different devices",
      "Deleting an Account": "Deleting an Account",
      "Delete account on": "Delete account on",
      "SafeVPN": "SafeVPN",
      "delete_desc":
          "1、After submitting, you will receive an email confirming the deletion, click the link in the email to complete the account deletion.2、 This will delete all your data and it cannot be recovered.",
      "Submit": "Submit",
      "Email has been sent": "Email has been sent",
      "send_email_desc":
          "Please go to your mailbox to receive the email, and click the link in the email to complete the account deletion.",
      "Account has been": "Account has been",
      "deleted": "deleted",
      "Return Home": "Return Home",
      "Verification": "Verification",
      "Resend code in": "Resend code in ",
      "verification_desc":
          "We have sent a verification code to your email. Please enter that code to complete",
      "Bind Referrer": "Bind Referrer",
      "Enter points": "Enter points",
      "Referrer code": "Referrer code",
      "Withdraw": "Withdraw",
      "Assets": "Assets",
      "Points": "Points",
      "Enter account": "Enter account",
      "Account": "Account",
      "Enter name": "Enter name",
      "Name": "Name",
    },
    'nl_NL': {
      'appName': 'safeVpn',
      'FIX': 'FIX',
      "VPN": "VPN",
      'Log in': 'Log in',
      'Sign Up': 'Sign Up',
      'Enter email address': "Enter email address",
      'Email Address': "Email Address",
      'By signing up,I agree to the': "By signing up,I agree to the ",
      'private policy': "private policy",
      'Log in with Google': "Log in with Google",
      'Get A Plan': "Get A Plan",
      'That Works For You': "That Works For You",
      'sub_desc':
          "Stable and 10 times high speed Watch HD videos without freezing Remove annoyed Ads banners Connect up to 5 different devices",
      "Deleting an Account": "Deleting an Account",
      "Delete account on": "Delete account on",
      "SafeVPN": "SafeVPN",
      "delete_desc":
          "1、After submitting, you will receive an email confirming the deletion, click the link in the email to complete the account deletion.2、 This will delete all your data and it cannot be recovered.",
      "Submit": "Submit",
      "Email has been sent": "Email has been sent",
      "send_email_desc":
          "Please go to your mailbox to receive the email, and click the link in the email to complete the account deletion.",
      "Account has been": "Account has been",
      "deleted": "deleted",
      "Return Home": "Return Home",
      "Verification": "Verification",
      "Resend code in": "Resend code in ",
      "verification_desc":
          "We have sent a verification code to your email. Please enter that code to complete",
      "Bind Referrer": "Bind Referrer",
      "Enter points": "Enter points",
      "Referrer code": "Referrer code",
      "Withdraw": "Withdraw",
      "Assets": "Assets",
      "Points": "Points",
      "Enter account": "Enter account",
      "Account": "Account",
      "Enter name": "Enter name",
      "Name": "Name",
    },
    'pt_BR': {
      'appName': 'safeVpn',
      'FIX': 'FIX',
      "VPN": "VPN",
      'Log in': 'Log in',
      'Sign Up': 'Sign Up',
      'Enter email address': "Enter email address",
      'Email Address': "Email Address",
      'By signing up,I agree to the': "By signing up,I agree to the ",
      'private policy': "private policy",
      'Log in with Google': "Log in with Google",
      'Get A Plan': "Get A Plan",
      'That Works For You': "That Works For You",
      'sub_desc':
          "Stable and 10 times high speed Watch HD videos without freezing Remove annoyed Ads banners Connect up to 5 different devices",
      "Deleting an Account": "Deleting an Account",
      "Delete account on": "Delete account on",
      "SafeVPN": "SafeVPN",
      "delete_desc":
          "1、After submitting, you will receive an email confirming the deletion, click the link in the email to complete the account deletion.2、 This will delete all your data and it cannot be recovered.",
      "Submit": "Submit",
      "Email has been sent": "Email has been sent",
      "send_email_desc":
          "Please go to your mailbox to receive the email, and click the link in the email to complete the account deletion.",
      "Account has been": "Account has been",
      "deleted": "deleted",
      "Return Home": "Return Home",
      "Verification": "Verification",
      "Resend code in": "Resend code in ",
      "verification_desc":
          "We have sent a verification code to your email. Please enter that code to complete",
      "Bind Referrer": "Bind Referrer",
      "Enter points": "Enter points",
      "Referrer code": "Referrer code",
      "Withdraw": "Withdraw",
      "Assets": "Assets",
      "Points": "Points",
      "Enter account": "Enter account",
      "Account": "Account",
      "Enter name": "Enter name",
      "Name": "Name",
    },
    'ru_RU': {
      'appName': 'safeVpn',
      'FIX': 'FIX',
      "VPN": "VPN",
      'Log in': 'Log in',
      'Sign Up': 'Sign Up',
      'Enter email address': "Enter email address",
      'Email Address': "Email Address",
      'By signing up,I agree to the': "By signing up,I agree to the ",
      'private policy': "private policy",
      'Log in with Google': "Log in with Google",
      'Get A Plan': "Get A Plan",
      'That Works For You': "That Works For You",
      'sub_desc':
          "Stable and 10 times high speed Watch HD videos without freezing Remove annoyed Ads banners Connect up to 5 different devices",
      "Deleting an Account": "Deleting an Account",
      "Delete account on": "Delete account on",
      "SafeVPN": "SafeVPN",
      "delete_desc":
          "1、After submitting, you will receive an email confirming the deletion, click the link in the email to complete the account deletion.2、 This will delete all your data and it cannot be recovered.",
      "Submit": "Submit",
      "Email has been sent": "Email has been sent",
      "send_email_desc":
          "Please go to your mailbox to receive the email, and click the link in the email to complete the account deletion.",
      "Account has been": "Account has been",
      "deleted": "deleted",
      "Return Home": "Return Home",
      "Verification": "Verification",
      "Resend code in": "Resend code in ",
      "verification_desc":
          "We have sent a verification code to your email. Please enter that code to complete",
      "Bind Referrer": "Bind Referrer",
      "Enter points": "Enter points",
      "Referrer code": "Referrer code",
      "Withdraw": "Withdraw",
      "Assets": "Assets",
      "Points": "Points",
      "Enter account": "Enter account",
      "Account": "Account",
      "Enter name": "Enter name",
      "Name": "Name",
    },
    'th_TH': {
      'appName': 'safeVpn',
      'FIX': 'FIX',
      "VPN": "VPN",
      'Log in': 'Log in',
      'Sign Up': 'Sign Up',
      'Enter email address': "Enter email address",
      'Email Address': "Email Address",
      'By signing up,I agree to the': "By signing up,I agree to the ",
      'private policy': "private policy",
      'Log in with Google': "Log in with Google",
      'Get A Plan': "Get A Plan",
      'That Works For You': "That Works For You",
      'sub_desc':
          "Stable and 10 times high speed Watch HD videos without freezing Remove annoyed Ads banners Connect up to 5 different devices",
      "Deleting an Account": "Deleting an Account",
      "Delete account on": "Delete account on",
      "SafeVPN": "SafeVPN",
      "delete_desc":
          "1、After submitting, you will receive an email confirming the deletion, click the link in the email to complete the account deletion.2、 This will delete all your data and it cannot be recovered.",
      "Submit": "Submit",
      "Email has been sent": "Email has been sent",
      "send_email_desc":
          "Please go to your mailbox to receive the email, and click the link in the email to complete the account deletion.",
      "Account has been": "Account has been",
      "deleted": "deleted",
      "Return Home": "Return Home",
      "Verification": "Verification",
      "Resend code in": "Resend code in ",
      "verification_desc":
          "We have sent a verification code to your email. Please enter that code to complete",
      "Bind Referrer": "Bind Referrer",
      "Enter points": "Enter points",
      "Referrer code": "Referrer code",
      "Withdraw": "Withdraw",
      "Assets": "Assets",
      "Points": "Points",
      "Enter account": "Enter account",
      "Account": "Account",
      "Enter name": "Enter name",
      "Name": "Name",
    },
    'tl_PH': {
      'appName': 'safeVpn',
      'FIX': 'FIX',
      "VPN": "VPN",
      'Log in': 'Log in',
      'Sign Up': 'Sign Up',
      'Enter email address': "Enter email address",
      'Email Address': "Email Address",
      'By signing up,I agree to the': "By signing up,I agree to the ",
      'private policy': "private policy",
      'Log in with Google': "Log in with Google",
      'Get A Plan': "Get A Plan",
      'That Works For You': "That Works For You",
      'sub_desc':
          "Stable and 10 times high speed Watch HD videos without freezing Remove annoyed Ads banners Connect up to 5 different devices",
      "Deleting an Account": "Deleting an Account",
      "Delete account on": "Delete account on",
      "SafeVPN": "SafeVPN",
      "delete_desc":
          "1、After submitting, you will receive an email confirming the deletion, click the link in the email to complete the account deletion.2、 This will delete all your data and it cannot be recovered.",
      "Submit": "Submit",
      "Email has been sent": "Email has been sent",
      "send_email_desc":
          "Please go to your mailbox to receive the email, and click the link in the email to complete the account deletion.",
      "Account has been": "Account has been",
      "deleted": "deleted",
      "Return Home": "Return Home",
      "Verification": "Verification",
      "Resend code in": "Resend code in ",
      "verification_desc":
          "We have sent a verification code to your email. Please enter that code to complete",
      "Bind Referrer": "Bind Referrer",
      "Enter points": "Enter points",
      "Referrer code": "Referrer code",
      "Withdraw": "Withdraw",
      "Assets": "Assets",
      "Points": "Points",
      "Enter account": "Enter account",
      "Account": "Account",
      "Enter name": "Enter name",
      "Name": "Name",
    },
    'tr_TR': {
      'appName': 'safeVpn',
      'FIX': 'FIX',
      "VPN": "VPN",
      'Log in': 'Log in',
      'Sign Up': 'Sign Up',
      'Enter email address': "Enter email address",
      'Email Address': "Email Address",
      'By signing up,I agree to the': "By signing up,I agree to the ",
      'private policy': "private policy",
      'Log in with Google': "Log in with Google",
      'Get A Plan': "Get A Plan",
      'That Works For You': "That Works For You",
      'sub_desc':
          "Stable and 10 times high speed Watch HD videos without freezing Remove annoyed Ads banners Connect up to 5 different devices",
      "Deleting an Account": "Deleting an Account",
      "Delete account on": "Delete account on",
      "SafeVPN": "SafeVPN",
      "delete_desc":
          "1、After submitting, you will receive an email confirming the deletion, click the link in the email to complete the account deletion.2、 This will delete all your data and it cannot be recovered.",
      "Submit": "Submit",
      "Email has been sent": "Email has been sent",
      "send_email_desc":
          "Please go to your mailbox to receive the email, and click the link in the email to complete the account deletion.",
      "Account has been": "Account has been",
      "deleted": "deleted",
      "Return Home": "Return Home",
      "Verification": "Verification",
      "Resend code in": "Resend code in ",
      "verification_desc":
          "We have sent a verification code to your email. Please enter that code to complete",
      "Bind Referrer": "Bind Referrer",
      "Enter points": "Enter points",
      "Referrer code": "Referrer code",
      "Withdraw": "Withdraw",
      "Assets": "Assets",
      "Points": "Points",
      "Enter account": "Enter account",
      "Account": "Account",
      "Enter name": "Enter name",
      "Name": "Name",
    },
    'uk_UA': {
      'appName': 'safeVpn',
      'FIX': 'FIX',
      "VPN": "VPN",
      'Log in': 'Log in',
      'Sign Up': 'Sign Up',
      'Enter email address': "Enter email address",
      'Email Address': "Email Address",
      'By signing up,I agree to the': "By signing up,I agree to the ",
      'private policy': "private policy",
      'Log in with Google': "Log in with Google",
      'Get A Plan': "Get A Plan",
      'That Works For You': "That Works For You",
      'sub_desc':
          "Stable and 10 times high speed Watch HD videos without freezing Remove annoyed Ads banners Connect up to 5 different devices",
      "Deleting an Account": "Deleting an Account",
      "Delete account on": "Delete account on",
      "SafeVPN": "SafeVPN",
      "delete_desc":
          "1、After submitting, you will receive an email confirming the deletion, click the link in the email to complete the account deletion.2、 This will delete all your data and it cannot be recovered.",
      "Submit": "Submit",
      "Email has been sent": "Email has been sent",
      "send_email_desc":
          "Please go to your mailbox to receive the email, and click the link in the email to complete the account deletion.",
      "Account has been": "Account has been",
      "deleted": "deleted",
      "Return Home": "Return Home",
      "Verification": "Verification",
      "Resend code in": "Resend code in ",
      "verification_desc":
          "We have sent a verification code to your email. Please enter that code to complete",
      "Bind Referrer": "Bind Referrer",
      "Enter points": "Enter points",
      "Referrer code": "Referrer code",
      "Withdraw": "Withdraw",
      "Assets": "Assets",
      "Points": "Points",
      "Enter account": "Enter account",
      "Account": "Account",
      "Enter name": "Enter name",
      "Name": "Name",
    },
    'vi_VN': {
      'appName': 'safeVpn',
      'FIX': 'FIX',
      "VPN": "VPN",
      'Log in': 'Log in',
      'Sign Up': 'Sign Up',
      'Enter email address': "Enter email address",
      'Email Address': "Email Address",
      'By signing up,I agree to the': "By signing up,I agree to the ",
      'private policy': "private policy",
      'Log in with Google': "Log in with Google",
      'Get A Plan': "Get A Plan",
      'That Works For You': "That Works For You",
      'sub_desc':
          "Stable and 10 times high speed Watch HD videos without freezing Remove annoyed Ads banners Connect up to 5 different devices",
      "Deleting an Account": "Deleting an Account",
      "Delete account on": "Delete account on",
      "SafeVPN": "SafeVPN",
      "delete_desc":
          "1、After submitting, you will receive an email confirming the deletion, click the link in the email to complete the account deletion.2、 This will delete all your data and it cannot be recovered.",
      "Submit": "Submit",
      "Email has been sent": "Email has been sent",
      "send_email_desc":
          "Please go to your mailbox to receive the email, and click the link in the email to complete the account deletion.",
      "Account has been": "Account has been",
      "deleted": "deleted",
      "Return Home": "Return Home",
      "Verification": "Verification",
      "Resend code in": "Resend code in ",
      "verification_desc":
          "We have sent a verification code to your email. Please enter that code to complete",
      "Bind Referrer": "Bind Referrer",
      "Enter points": "Enter points",
      "Referrer code": "Referrer code",
      "Withdraw": "Withdraw",
      "Assets": "Assets",
      "Points": "Points",
      "Enter account": "Enter account",
      "Account": "Account",
      "Enter name": "Enter name",
      "Name": "Name",
    },
  };
}
